import type { ThaiCharacter } from "./schema";

/**
 * All 44 Thai consonants, grouped by class. Letter names, classes, and
 * sounds are public-domain script facts; the English glosses are our own.
 * RTGS romanization throughout.
 */
export const rawCharacters: ThaiCharacter[] = [
  // ── Mid class (9) ────────────────────────────────────────────────
  {
    id: "ko_kai",
    glyph: "ก",
    nameThai: "ก ไก่",
    nameRtgs: "ko kai",
    meaning: "chicken",
    class: "mid",
    initialSound: "k",
    finalSound: "k",
    audioKey: "consonants/ko_kai",
  },
  {
    id: "cho_chan",
    glyph: "จ",
    nameThai: "จ จาน",
    nameRtgs: "cho chan",
    meaning: "plate",
    class: "mid",
    initialSound: "ch",
    finalSound: "t",
    audioKey: "consonants/cho_chan",
  },
  {
    id: "do_chada",
    glyph: "ฎ",
    nameThai: "ฎ ชฎา",
    nameRtgs: "do chada",
    meaning: "headdress",
    class: "mid",
    initialSound: "d",
    finalSound: "t",
    audioKey: "consonants/do_chada",
    note: "Rare — appears mostly in words borrowed from Sanskrit and Pali.",
  },
  {
    id: "to_patak",
    glyph: "ฏ",
    nameThai: "ฏ ปฏัก",
    nameRtgs: "to patak",
    meaning: "goad",
    class: "mid",
    initialSound: "t",
    finalSound: "t",
    audioKey: "consonants/to_patak",
    note: "Rare — appears mostly in words borrowed from Sanskrit and Pali.",
  },
  {
    id: "do_dek",
    glyph: "ด",
    nameThai: "ด เด็ก",
    nameRtgs: "do dek",
    meaning: "child",
    class: "mid",
    initialSound: "d",
    finalSound: "t",
    audioKey: "consonants/do_dek",
  },
  {
    id: "to_tao",
    glyph: "ต",
    nameThai: "ต เต่า",
    nameRtgs: "to tao",
    meaning: "turtle",
    class: "mid",
    initialSound: "t",
    finalSound: "t",
    audioKey: "consonants/to_tao",
  },
  {
    id: "bo_baimai",
    glyph: "บ",
    nameThai: "บ ใบไม้",
    nameRtgs: "bo baimai",
    meaning: "leaf",
    class: "mid",
    initialSound: "b",
    finalSound: "p",
    audioKey: "consonants/bo_baimai",
  },
  {
    id: "po_pla",
    glyph: "ป",
    nameThai: "ป ปลา",
    nameRtgs: "po pla",
    meaning: "fish",
    class: "mid",
    initialSound: "p",
    finalSound: "p",
    audioKey: "consonants/po_pla",
  },
  {
    id: "o_ang",
    glyph: "อ",
    nameThai: "อ อ่าง",
    nameRtgs: "o ang",
    meaning: "basin",
    class: "mid",
    initialSound: "o",
    finalSound: null,
    audioKey: "consonants/o_ang",
    note: "Silent as a consonant — it carries vowels that need somewhere to sit.",
  },

  // ── High class (11) ──────────────────────────────────────────────
  {
    id: "kho_khai",
    glyph: "ข",
    nameThai: "ข ไข่",
    nameRtgs: "kho khai",
    meaning: "egg",
    class: "high",
    initialSound: "kh",
    finalSound: "k",
    audioKey: "consonants/kho_khai",
  },
  {
    id: "kho_khuat",
    glyph: "ฃ",
    nameThai: "ฃ ขวด",
    nameRtgs: "kho khuat",
    meaning: "bottle",
    class: "high",
    initialSound: "kh",
    finalSound: "k",
    audioKey: "consonants/kho_khuat",
    note: "Obsolete — no longer used in modern Thai.",
    obsolete: true,
  },
  {
    id: "cho_ching",
    glyph: "ฉ",
    nameThai: "ฉ ฉิ่ง",
    nameRtgs: "cho ching",
    meaning: "cymbals",
    class: "high",
    initialSound: "ch",
    finalSound: null,
    audioKey: "consonants/cho_ching",
  },
  {
    id: "tho_than",
    glyph: "ฐ",
    nameThai: "ฐ ฐาน",
    nameRtgs: "tho than",
    meaning: "pedestal",
    class: "high",
    initialSound: "th",
    finalSound: "t",
    audioKey: "consonants/tho_than",
  },
  {
    id: "tho_thung",
    glyph: "ถ",
    nameThai: "ถ ถุง",
    nameRtgs: "tho thung",
    meaning: "sack",
    class: "high",
    initialSound: "th",
    finalSound: "t",
    audioKey: "consonants/tho_thung",
  },
  {
    id: "pho_phueng",
    glyph: "ผ",
    nameThai: "ผ ผึ้ง",
    nameRtgs: "pho phueng",
    meaning: "bee",
    class: "high",
    initialSound: "ph",
    finalSound: null,
    audioKey: "consonants/pho_phueng",
  },
  {
    id: "fo_fa",
    glyph: "ฝ",
    nameThai: "ฝ ฝา",
    nameRtgs: "fo fa",
    meaning: "lid",
    class: "high",
    initialSound: "f",
    finalSound: null,
    audioKey: "consonants/fo_fa",
  },
  {
    id: "so_sala",
    glyph: "ศ",
    nameThai: "ศ ศาลา",
    nameRtgs: "so sala",
    meaning: "pavilion",
    class: "high",
    initialSound: "s",
    finalSound: "t",
    audioKey: "consonants/so_sala",
  },
  {
    id: "so_ruesi",
    glyph: "ษ",
    nameThai: "ษ ฤๅษี",
    nameRtgs: "so ruesi",
    meaning: "hermit",
    class: "high",
    initialSound: "s",
    finalSound: "t",
    audioKey: "consonants/so_ruesi",
  },
  {
    id: "so_suea",
    glyph: "ส",
    nameThai: "ส เสือ",
    nameRtgs: "so suea",
    meaning: "tiger",
    class: "high",
    initialSound: "s",
    finalSound: "t",
    audioKey: "consonants/so_suea",
  },
  {
    id: "ho_hip",
    glyph: "ห",
    nameThai: "ห หีบ",
    nameRtgs: "ho hip",
    meaning: "chest",
    class: "high",
    initialSound: "h",
    finalSound: null,
    audioKey: "consonants/ho_hip",
  },

  // ── Low class (24) ───────────────────────────────────────────────
  {
    id: "kho_khwai",
    glyph: "ค",
    nameThai: "ค ควาย",
    nameRtgs: "kho khwai",
    meaning: "buffalo",
    class: "low",
    initialSound: "kh",
    finalSound: "k",
    audioKey: "consonants/kho_khwai",
  },
  {
    id: "kho_khon",
    glyph: "ฅ",
    nameThai: "ฅ คน",
    nameRtgs: "kho khon",
    meaning: "person",
    class: "low",
    initialSound: "kh",
    finalSound: "k",
    audioKey: "consonants/kho_khon",
    note: "Obsolete — no longer used in modern Thai.",
    obsolete: true,
  },
  {
    id: "kho_rakhang",
    glyph: "ฆ",
    nameThai: "ฆ ระฆัง",
    nameRtgs: "kho rakhang",
    meaning: "bell",
    class: "low",
    initialSound: "kh",
    finalSound: "k",
    audioKey: "consonants/kho_rakhang",
  },
  {
    id: "ngo_ngu",
    glyph: "ง",
    nameThai: "ง งู",
    nameRtgs: "ngo ngu",
    meaning: "snake",
    class: "low",
    initialSound: "ng",
    finalSound: "ng",
    audioKey: "consonants/ngo_ngu",
  },
  {
    id: "cho_chang",
    glyph: "ช",
    nameThai: "ช ช้าง",
    nameRtgs: "cho chang",
    meaning: "elephant",
    class: "low",
    initialSound: "ch",
    finalSound: "t",
    audioKey: "consonants/cho_chang",
  },
  {
    id: "so_so",
    glyph: "ซ",
    nameThai: "ซ โซ่",
    nameRtgs: "so so",
    meaning: "chain",
    class: "low",
    initialSound: "s",
    finalSound: "t",
    audioKey: "consonants/so_so",
  },
  {
    id: "cho_choe",
    glyph: "ฌ",
    nameThai: "ฌ เฌอ",
    nameRtgs: "cho choe",
    meaning: "tree",
    class: "low",
    initialSound: "ch",
    finalSound: null,
    audioKey: "consonants/cho_choe",
  },
  {
    id: "yo_ying",
    glyph: "ญ",
    nameThai: "ญ หญิง",
    nameRtgs: "yo ying",
    meaning: "woman",
    class: "low",
    initialSound: "y",
    finalSound: "n",
    audioKey: "consonants/yo_ying",
  },
  {
    id: "tho_montho",
    glyph: "ฑ",
    nameThai: "ฑ มณโฑ",
    nameRtgs: "tho montho",
    meaning: "Montho (a queen in Thai legend)",
    class: "low",
    initialSound: "th",
    finalSound: "t",
    audioKey: "consonants/tho_montho",
  },
  {
    id: "tho_phuthao",
    glyph: "ฒ",
    nameThai: "ฒ ผู้เฒ่า",
    nameRtgs: "tho phuthao",
    meaning: "elder",
    class: "low",
    initialSound: "th",
    finalSound: "t",
    audioKey: "consonants/tho_phuthao",
  },
  {
    id: "no_nen",
    glyph: "ณ",
    nameThai: "ณ เณร",
    nameRtgs: "no nen",
    meaning: "novice monk",
    class: "low",
    initialSound: "n",
    finalSound: "n",
    audioKey: "consonants/no_nen",
  },
  {
    id: "tho_thahan",
    glyph: "ท",
    nameThai: "ท ทหาร",
    nameRtgs: "tho thahan",
    meaning: "soldier",
    class: "low",
    initialSound: "th",
    finalSound: "t",
    audioKey: "consonants/tho_thahan",
  },
  {
    id: "tho_thong",
    glyph: "ธ",
    nameThai: "ธ ธง",
    nameRtgs: "tho thong",
    meaning: "flag",
    class: "low",
    initialSound: "th",
    finalSound: "t",
    audioKey: "consonants/tho_thong",
  },
  {
    id: "no_nu",
    glyph: "น",
    nameThai: "น หนู",
    nameRtgs: "no nu",
    meaning: "mouse",
    class: "low",
    initialSound: "n",
    finalSound: "n",
    audioKey: "consonants/no_nu",
  },
  {
    id: "pho_phan",
    glyph: "พ",
    nameThai: "พ พาน",
    nameRtgs: "pho phan",
    meaning: "tray",
    class: "low",
    initialSound: "ph",
    finalSound: "p",
    audioKey: "consonants/pho_phan",
  },
  {
    id: "fo_fan",
    glyph: "ฟ",
    nameThai: "ฟ ฟัน",
    nameRtgs: "fo fan",
    meaning: "teeth",
    class: "low",
    initialSound: "f",
    finalSound: "p",
    audioKey: "consonants/fo_fan",
  },
  {
    id: "pho_samphao",
    glyph: "ภ",
    nameThai: "ภ สำเภา",
    nameRtgs: "pho samphao",
    meaning: "sailing ship",
    class: "low",
    initialSound: "ph",
    finalSound: "p",
    audioKey: "consonants/pho_samphao",
  },
  {
    id: "mo_ma",
    glyph: "ม",
    nameThai: "ม ม้า",
    nameRtgs: "mo ma",
    meaning: "horse",
    class: "low",
    initialSound: "m",
    finalSound: "m",
    audioKey: "consonants/mo_ma",
  },
  {
    id: "yo_yak",
    glyph: "ย",
    nameThai: "ย ยักษ์",
    nameRtgs: "yo yak",
    meaning: "giant",
    class: "low",
    initialSound: "y",
    finalSound: "y",
    audioKey: "consonants/yo_yak",
  },
  {
    id: "ro_ruea",
    glyph: "ร",
    nameThai: "ร เรือ",
    nameRtgs: "ro ruea",
    meaning: "boat",
    class: "low",
    initialSound: "r",
    finalSound: "n",
    audioKey: "consonants/ro_ruea",
  },
  {
    id: "lo_ling",
    glyph: "ล",
    nameThai: "ล ลิง",
    nameRtgs: "lo ling",
    meaning: "monkey",
    class: "low",
    initialSound: "l",
    finalSound: "n",
    audioKey: "consonants/lo_ling",
  },
  {
    id: "wo_waen",
    glyph: "ว",
    nameThai: "ว แหวน",
    nameRtgs: "wo waen",
    meaning: "ring",
    class: "low",
    initialSound: "w",
    finalSound: "w",
    audioKey: "consonants/wo_waen",
  },
  {
    id: "lo_chula",
    glyph: "ฬ",
    nameThai: "ฬ จุฬา",
    nameRtgs: "lo chula",
    meaning: "kite",
    class: "low",
    initialSound: "l",
    finalSound: "n",
    audioKey: "consonants/lo_chula",
  },
  {
    id: "ho_nokhuk",
    glyph: "ฮ",
    nameThai: "ฮ นกฮูก",
    nameRtgs: "ho nokhuk",
    meaning: "owl",
    class: "low",
    initialSound: "h",
    finalSound: null,
    audioKey: "consonants/ho_nokhuk",
  },
];
