import type { ThaiVowel } from "./schema";

/**
 * The Phase-1 vowel inventory: nine short/long pairs plus the common
 * complex vowels. ◌ (U+25CC) marks where the consonant sits. Rare ฤ ฦ and
 * the ◌ั/◌็ spelling variants are out of scope (mentioned in concept notes
 * only). Vowel facts are public-domain script knowledge; glosses are ours.
 */
export const rawVowels: ThaiVowel[] = [
  // ── Short/long pairs ─────────────────────────────────────────────
  {
    kind: "vowel",
    id: "sara_a_short",
    glyph: "◌ะ",
    nameThai: "สระ อะ",
    nameRtgs: "sara a",
    sound: "a",
    length: "short",
    position: "after",
    audioKey: "vowels/sara_a_short",
  },
  {
    kind: "vowel",
    id: "sara_a_long",
    glyph: "◌า",
    nameThai: "สระ อา",
    nameRtgs: "sara a",
    sound: "a",
    length: "long",
    position: "after",
    audioKey: "vowels/sara_a_long",
  },
  {
    kind: "vowel",
    id: "sara_i_short",
    glyph: "◌ิ",
    nameThai: "สระ อิ",
    nameRtgs: "sara i",
    sound: "i",
    length: "short",
    position: "above",
    audioKey: "vowels/sara_i_short",
  },
  {
    kind: "vowel",
    id: "sara_i_long",
    glyph: "◌ี",
    nameThai: "สระ อี",
    nameRtgs: "sara i",
    sound: "i",
    length: "long",
    position: "above",
    audioKey: "vowels/sara_i_long",
  },
  {
    kind: "vowel",
    id: "sara_ue_short",
    glyph: "◌ึ",
    nameThai: "สระ อึ",
    nameRtgs: "sara ue",
    sound: "ue",
    length: "short",
    position: "above",
    audioKey: "vowels/sara_ue_short",
  },
  {
    kind: "vowel",
    id: "sara_ue_long",
    glyph: "◌ือ",
    nameThai: "สระ อือ",
    nameRtgs: "sara ue",
    sound: "ue",
    length: "long",
    position: "around",
    audioKey: "vowels/sara_ue_long",
    note: "Written ◌ื above plus อ after — the อ drops when a final consonant follows.",
  },
  {
    kind: "vowel",
    id: "sara_u_short",
    glyph: "◌ุ",
    nameThai: "สระ อุ",
    nameRtgs: "sara u",
    sound: "u",
    length: "short",
    position: "below",
    audioKey: "vowels/sara_u_short",
  },
  {
    kind: "vowel",
    id: "sara_u_long",
    glyph: "◌ู",
    nameThai: "สระ อู",
    nameRtgs: "sara u",
    sound: "u",
    length: "long",
    position: "below",
    audioKey: "vowels/sara_u_long",
  },
  {
    kind: "vowel",
    id: "sara_e_short",
    glyph: "เ◌ะ",
    nameThai: "สระ เอะ",
    nameRtgs: "sara e",
    sound: "e",
    length: "short",
    position: "around",
    audioKey: "vowels/sara_e_short",
  },
  {
    kind: "vowel",
    id: "sara_e_long",
    glyph: "เ◌",
    nameThai: "สระ เอ",
    nameRtgs: "sara e",
    sound: "e",
    length: "long",
    position: "before",
    audioKey: "vowels/sara_e_long",
    note: "Written before the consonant it follows in speech — read the consonant first.",
  },
  {
    kind: "vowel",
    id: "sara_ae_short",
    glyph: "แ◌ะ",
    nameThai: "สระ แอะ",
    nameRtgs: "sara ae",
    sound: "ae",
    length: "short",
    position: "around",
    audioKey: "vowels/sara_ae_short",
  },
  {
    kind: "vowel",
    id: "sara_ae_long",
    glyph: "แ◌",
    nameThai: "สระ แอ",
    nameRtgs: "sara ae",
    sound: "ae",
    length: "long",
    position: "before",
    audioKey: "vowels/sara_ae_long",
  },
  {
    kind: "vowel",
    id: "sara_o_short",
    glyph: "โ◌ะ",
    nameThai: "สระ โอะ",
    nameRtgs: "sara o",
    sound: "o",
    length: "short",
    position: "around",
    audioKey: "vowels/sara_o_short",
  },
  {
    kind: "vowel",
    id: "sara_o_long",
    glyph: "โ◌",
    nameThai: "สระ โอ",
    nameRtgs: "sara o",
    sound: "o",
    length: "long",
    position: "before",
    audioKey: "vowels/sara_o_long",
  },
  {
    kind: "vowel",
    id: "sara_o_open_short",
    glyph: "เ◌าะ",
    nameThai: "สระ เอาะ",
    nameRtgs: "sara o",
    sound: "o (open)",
    length: "short",
    position: "around",
    audioKey: "vowels/sara_o_open_short",
    note: "The open o, as in English “ought” said short.",
  },
  {
    kind: "vowel",
    id: "sara_o_open_long",
    glyph: "◌อ",
    nameThai: "สระ ออ",
    nameRtgs: "sara o",
    sound: "o (open)",
    length: "long",
    position: "after",
    audioKey: "vowels/sara_o_open_long",
    note: "อ doing vowel duty: after a consonant it writes the long open o.",
  },
  {
    kind: "vowel",
    id: "sara_oe_short",
    glyph: "เ◌อะ",
    nameThai: "สระ เออะ",
    nameRtgs: "sara oe",
    sound: "oe",
    length: "short",
    position: "around",
    audioKey: "vowels/sara_oe_short",
  },
  {
    kind: "vowel",
    id: "sara_oe_long",
    glyph: "เ◌อ",
    nameThai: "สระ เออ",
    nameRtgs: "sara oe",
    sound: "oe",
    length: "long",
    position: "around",
    audioKey: "vowels/sara_oe_long",
  },

  // ── Complex vowels ───────────────────────────────────────────────
  {
    kind: "vowel",
    id: "sara_ia",
    glyph: "เ◌ีย",
    nameThai: "สระ เอีย",
    nameRtgs: "sara ia",
    sound: "ia",
    length: "long",
    position: "around",
    audioKey: "vowels/sara_ia",
  },
  {
    kind: "vowel",
    id: "sara_uea",
    glyph: "เ◌ือ",
    nameThai: "สระ เอือ",
    nameRtgs: "sara uea",
    sound: "uea",
    length: "long",
    position: "around",
    audioKey: "vowels/sara_uea",
  },
  {
    kind: "vowel",
    id: "sara_ua",
    glyph: "◌ัว",
    nameThai: "สระ อัว",
    nameRtgs: "sara ua",
    sound: "ua",
    length: "long",
    position: "around",
    audioKey: "vowels/sara_ua",
    note: "Loses the ◌ั and becomes ◌ว when a final consonant follows.",
  },
  {
    kind: "vowel",
    id: "sara_ai_maimalai",
    glyph: "ไ◌",
    nameThai: "สระ ไอ (ไม้มลาย)",
    nameRtgs: "sara ai (mai malai)",
    sound: "ai",
    length: "short",
    position: "before",
    audioKey: "vowels/sara_ai_maimalai",
    note: "Counts as a live syllable for tone rules — it ends in a glide.",
  },
  {
    kind: "vowel",
    id: "sara_ai_maimuan",
    glyph: "ใ◌",
    nameThai: "สระ ใอ (ไม้ม้วน)",
    nameRtgs: "sara ai (mai muan)",
    sound: "ai",
    length: "short",
    position: "before",
    audioKey: "vowels/sara_ai_maimuan",
    note: "Same sound as ไ◌ but used in only about twenty Thai words. Live for tone rules.",
  },
  {
    kind: "vowel",
    id: "sara_ao",
    glyph: "เ◌า",
    nameThai: "สระ เอา",
    nameRtgs: "sara ao",
    sound: "ao",
    length: "short",
    position: "around",
    audioKey: "vowels/sara_ao",
    note: "Counts as a live syllable for tone rules — it ends in a glide.",
  },
  {
    kind: "vowel",
    id: "sara_am",
    glyph: "◌ำ",
    nameThai: "สระ อำ",
    nameRtgs: "sara am",
    sound: "am",
    length: "short",
    position: "after",
    audioKey: "vowels/sara_am",
    note: "Counts as a live syllable for tone rules — it ends in the sonorant m.",
  },
];
